### ISSUE TITLE
Integration stuck on starting configuration

### ISSUE THREAD

**Issue by marcokreeft87** [Sholofly/lghorizon#1]
**Describe the bug**
Integration stuck on starting configuration

**To Reproduce**
1. Manual installation
2. Go to integrations and search for LG Horizon
3. Click on LG horizon

**Expected behavior**
A config screen appears

**Screenshots**
![image](https://user-images.githubusercontent.com/10223677/196188555-86851a27-7edc-4f20-aac7-f3e06db73306.png)

I've got no error in log

**Comment by Sholofly** [comment]
@marcokreeft87  I had this too the first time. And there were no errors in the log. Even when set to debug.
I'm not sure what solved the problem at my side. Browser cache or extra reboot of HA. Please give both a try.

**Comment by marcokreeft87** [comment]
Multiple tries works. Not ideal, but it works :) Your call if you want to close this issue

**Comment by Sholofly** [comment]
I'll keep this open for a while. If there are more people that experience the same issue then i'm going to investigate it deeper.

**Comment by marcokreeft87** [comment]
Other than the start, its working good so far. Controlling the mediabox wise, I think it even works better than the old version

**Comment by Sholofly** [comment]
Sounds good, just curious:  What does you make saying  "I think it even works better than the old version"?

**Comment by marcokreeft87** [comment]
On the old version, when I turned it on, sometimes it didnt work. Or when I switched channel. Now it works instantly. Did you do something different on this integration?

**Comment by Sholofly** [comment]
I rebuilt it from scratch. With improved error handling and cleaner code!

**Comment by marcokreeft87** [comment]
Well it paying off!

**Comment by Wvanlaa** [comment]
Just did install, worked first time around. Took couple of seconds to provide configuration dialog, but nothing spectacular. Because I was actually troubleshooting the previous (Arris) integration I had done all of the precautions before:
1) power-off / on Next 2) clear browser cache 3) reloaded HA (after completely removing all the previous integration).
Thanks Sholofly!,
Using Ziggo.

**Comment by Sholofly** [comment]
Ok thanks for the test! I'm closing it now.

**Comment by caraar12345** [comment]
Did anyone ever work this one out? 👀 

Despite sorting the auth, I can't actually get it set up -- and clearing the cache, restarting HA etc doesn't seem to be sorting it 😭 

![image](https://user-images.githubusercontent.com/6129428/208903452-4a0cd39a-0023-4183-a0bf-0ba900085604.png)

I've tried profiling HA, checking logs etc but nothing's coming up which is just... weird.
