### ISSUE TITLE
Can't select radio station in the ziggo intergration

### ISSUE THREAD

**Issue by Rensvanherwaarden** [Sholofly/lghorizon#10]
When i select a radio station like 'radio 538` in de mediaplayer in home assistant.  I see a response from my media box but te station is not selected or shown on my tv. 

The media box gives the message " Deze titel is naar je tv gestuurd vanaf home assistant" but the input is not changed

**Comment by Sholofly** [comment]
Hi @Rensvanherwaarden Unfortunately it isn't possible to select a radio channel from the component. I will release an update soon to remove radio channels from the channels list

**Comment by Sholofly** [comment]
I removed the radio station in latest version 0.3.3
