### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by RobDiederen** [Sholofly/lghorizon#106]
The automation stopped working today. 
Couldn't reload LG Horizon anymore.
Try to reinstall the add-on but it freezes after entering username and password.

**Comment by Sholofly** [comment]
Logs? Version?

**Comment by Sholofly** [comment]
Comon! I really want to help you but how am I supposed to deal with your issue without any form of info

**Comment by RobDiederen** [comment]
I tried reinstalling version v0.5.9, but It didn't add the Integration anymore, after entering username and password. Double checked username and password where correct in my ziggo go app. 
Just managed to install the integration, but all equipment is turned off downstairs. I will try tomorrow if the integration/mediabox responds.

**Comment by funip** [comment]
Same problem issues here.
Fisrt the enties stopped working and i had to initialize the lghorizon integration but that wasn't working. 
so i removed it also from HACS and deleted all files from custom_components.
rebooted Hass and downloaded from HACS rebooted again and added the LGhorizon intergration, setup info for ziggo media box next mini. Provider ziggo and its username and passwd
ingration geeps loading and after a while error  cannot connect

**Comment by RobDiederen** [comment]
After duplicating the broken automations and removing the broken ones it works again.  (basically renewing the same automations)
So yesterday I removed the integration, reinstalled the LG Horizon integration (without removing it from HACS) . I was able to install the integration by using my username and password for Ziggo yesterday, after fixing the automations today it works again. Hope this helps

**Comment by funip** [comment]
I romeved the whole directory from custom_componenets from terminal. (rm -rf config/custom_components/lghorizon)
removed all entities installed again from HACS and with update 20 minutes ago that fixed my problem.

**Comment by Sholofly** [comment]
Good to hear it works again.
