### ISSUE TITLE
LG Horizon unavailable again and breaking HA as last time

### ISSUE THREAD

**Issue by canedje** [Sholofly/lghorizon#107]
**Describe the bug**
Suddenly the LG Horizon integration was unavailable
Restarting integration didn't work giving initializing error
After restarting HA, HA is not starting anymore. Hanging on LG-Horizon integration
Like problem before last week
https://github.com/Sholofly/lghorizon/issues/100
Difference is not a real error code in LOG, only warning about waiting for integration

EDIT: I did the steps again as mentioned here above. switch off integration, restart HA, starting integration again after startup HA.
LG Horizon, Up and running.
Is now up and running for 15 minutes

I switched off LG-Horizon integration. Restarted HA. (HACS part still running)
HA is starting again.
After restart without LG Horizon integration, I did start the integration and it is working again???
After some minutes Integration not available again
![image](https://github.com/Sholofly/lghorizon/assets/23150947/e8896471-d5c3-45e5-9a9a-42145b4206df)
After reload the integration Initialize problem again
![image](https://github.com/Sholofly/lghorizon/assets/23150947/6196022d-8de2-478e-ac85-be53306fa8d6)
After restart HA hangig again on LG Horizon integration
![image](https://github.com/Sholofly/lghorizon/assets/23150947/b5e8a827-748c-461a-9e90-55d67e358c14)
Not a real error in LOG
![image](https://github.com/Sholofly/lghorizon/assets/23150947/d9f481bb-14c3-437d-a820-edfef254ad0a)
I need to switch off LG Horizon to get HA up and running again

EDIT2: I did the procedure as mentioned here above: Switch off LG Horizon integration. Restart HA. Start LG Horizon integration again.
LG Horizon is up and running (Now for 15 minutes already)

EDIT3:
Still not running as aspected.
After switching off the TV (next mini)
The integration still says playing:
![image](https://github.com/Sholofly/lghorizon/assets/23150947/8063daa8-f9ba-4a8e-8c49-3e8657d83d95)

EDIT4:
This happened several times yesterday evening. Now it is running again.
I think GHeiner is right. A temporary problem with the API at Ziggo?

**To Reproduce**
Nothing todo it just happens
**Expected behavior**

**Screenshots**

**Version of the component**
v0.5.9

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by GHeiner** [comment]
I've encountered the same.

When try to install the LGHorizon integration get get this in my logging
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 20:15:08 (1 occurrences)
Last logged: 20:15:08

Error setting up entry gerard@heiner.nl for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError


after trying again the problem is gone. Maybe a glitch at Ziggo?

**Comment by canedje** [comment]
Not happened anymore. Issue can be closed
