### ISSUE TITLE
LGhorizon intergration is running  Command not send

### ISSUE THREAD

**Issue by Rotil66** [Sholofly/lghorizon#108]
Hi Sholofly,
I'm using the LGhorizon intergration for a long time. I had this known login issue lately that was solved with the 0.5.9 versie. 
But now I have a strange issue I can't pinpoint... The integration is running and is not reporting an error. I have made button that send the command to my ziggo next. These have been working flawless. but now they constantly stop working randomly. After a restart of HA Incan send one or two command and then it stops. Sometime they are back at a moment just to stop again. I don' t have a clue.... Any Idea's ????
Thanks

**Comment by Sholofly** [comment]
Aren't there messages in the log either? Did you enable debug logging for the component?

**Comment by Rotil66** [comment]
Hi Sholofly,
I posted this message quite a long time ago so I forgot it was still open. Somewhere alone the line the intergration started to work flawless again and has been ever since. Even better, I can now control the Next when I'm in the 3th party apps. That has never worked before.
So thanks for you efforts making/supporting this intergration !!!
Kind regard,
Rolof

**Comment by Sholofly** [comment]
You're welcome!
