### ISSUE TITLE
LH Horizon integration not working

### ISSUE THREAD

**Issue by Ton174** [Sholofly/lghorizon#109]
The LG horizon ziggo integration (ziggo next mini) has been working excellent in the past year.
Then it stopped working because the media player-2 was not available anymore.

I tried to solve the problem by uninstalling and then reinstalling the integration.
After filling in the LG Horizon details the integration keeps "processing" (=nothing happens).

In the logfile I found the following error:

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)

The HA  configuration is:
Core  2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1

ps 1
Recently Ziggo introduced a mandatory twostep verification process for logging in to a ziggo account.
I was wondering if this also applies to an api-call
ps 2
I logged in to the zigogo app on my phone and was able to access the ziggo next mini. 

I am not an experience HA user. So please let me know if you need more information

Thanks in advance, Ton

**Comment by kroona** [comment]
Same issue here, look likes the 2fa issue.

**Comment by kroona** [comment]
Remove all the files from custom components and reinstall via Hacs. That fixed it for me.

**Comment by Ton174** [comment]
Hi kroona,
Thanks for the great tip.
It is working again!
