### ISSUE TITLE
Send letter keys not only numbers

### ISSUE THREAD

**Issue by filip-heens** [Sholofly/lghorizon#112]
**Is your feature request related to a problem? Please describe.**
When I go to the menu and start a search the keyboard doesn't show, so I can't use it.. I created a small keyboard with the lovelace but the letter keys aren't send to the device

**Describe the solution you'd like**
Being able to send the letters via HA

This is the code used for the letter A
      tap_action:
          action: call-service
          service: lghorizon.remote_key_press
          service_data:
            entity_id: media_player.boven
            remote_key: A

**Comment by Sholofly** [comment]
Hi @filip-heens, Unfortunately this is not possible. There are no letters on the remote, and this service mimics the remote. Unless you have a different remote than me (see readme) this is not possible.
