### ISSUE TITLE
Reduce time out when integration fails

### ISSUE THREAD

**Issue by JATD2020** [Sholofly/lghorizon#113]
Would it be possible to reduce the time that it takes for the integration to fail? 

Last week when there were issues with the integration it took a very very long time for the integration to timeout/fail and let HA continue the startup process. 
Would it be possible to reduce the timeout to maybe 30 seconds or 1 minute? 

Great work by the way on this integration!

**Comment by JATD2020** [comment]
@Sholofly is this something that can be changed? I had some issues with the integration again last week (not the fault of the integration), but then restarting home assistant seems to take forever because it hangs on LG Horizon. Can we change this timeout?

**Comment by Sholofly** [comment]
Changed the timeout so it tries only 3 times.
