### ISSUE TITLE
Fail to setup

### ISSUE THREAD

**Issue by snhnic** [Sholofly/lghorizon#115]
Suddenly not working anymore fail to setup (Ziggo account). Is this a problem my side or is it something Ziggo has changed?

**Comment by JBakers** [comment]
Same for me, since last night not able to initialize.
Removed the integration totally, as per suggestions from recent closed issues, but cannot finish the setup when logging in with my Ziggo details.

Will edit this post soon with debug log

**Comment by filip-heens** [comment]
Issue is due to expired horizon.tv SSL certificate 😉 ☹
See issue 114 for more information
Guess we’ll have to wait ☹

**Comment by JBakers** [comment]
Aaah this is the same as #114

**Comment by canedje** [comment]
Same for me after this evening.
Not able to initialize again after restart
Indeed: I do see a SSL certificate error in the logs

**Comment by snhnic** [comment]
It’s working again
