### ISSUE TITLE
Virgin Stream Box

### ISSUE THREAD

**Issue by cooltings** [Sholofly/lghorizon#117]
Hi just wondering if the virgin stream box is supported?
![image](https://github.com/Sholofly/lghorizon/assets/104278596/81743848-26fd-4e8a-b627-c86d517b7ae1)

**Comment by Sholofly** [comment]
Yes, the hardware is. I have the same at home. But there are some other issues regarding accounts that have effect on Virgin too.

**Comment by cooltings** [comment]
So there is no way to control this?

**Comment by Sholofly** [comment]
No, for now.
