### ISSUE TITLE
No more connection to ziggo next mini

### ISSUE THREAD

**Issue by T-tronicks** [Sholofly/lghorizon#120]
Hello,
Sinds last night there is no connection to the ziggo next mini anymore.
I've tried to initialize, but no succes.

Reading through other issues here I've tried removing the LG horizon integration, and reinstalling.
But when I try to setup with my credentials, nothing happens...

In the log files the following massage is found.

*********
Logger: lghorizon.lghorizon_api
Bron: /usr/local/lib/python3.12/site-packages/backoff/_common.py:120
Eerst voorgekomen: 09:44:52 (31 gebeurtenissen)
Laatst gelogd: 09:55:32

Giving up _authorize(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Account locked)
Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Account locked)
***********

The message appeared when initialize and when I try to setup after reinstalling the integration. 

Every help is welcome.

Thanks in advance

**Comment by Sholofly** [comment]
Hi @T-tronicks, Thanks for your report. I guess the account locked is about too many retries, although I think I have that covered in the component.

I experiencing an issue with unavailable boxes, but in the logs it looks like everything goes well. Probably LG has changed something in their API. I am going to look at it but don't know when exactly.

**Comment by T-tronicks** [comment]
Hello sholofly,
I've tried to run the setup again 30 min ago.
And now the boxes immediately where found and added.
Everything works perfect again.
I don't know what the problem was this morning,  probably a issue beyond HA or the integration. 

I'm happy again.
Thank you for this perfect integration and your help.

Best regards 
Nick

**Comment by canedje** [comment]
This happened to me just a minute ago also.
It did work until now for a long time
No connection
I don't see any reason


EDIT: Same here. After15 minutes it is working again

**Comment by Sholofly** [comment]
Ok, looks like a hickup that causes to many retries, and that temporarily locked you out.  That's taken account in #113. Will close this one for now.
