### ISSUE TITLE
Support for BASE TV-Box

### ISSUE THREAD

**Issue by Nicoautoxp** [Sholofly/lghorizon#121]
**Is your feature request related to a problem? Please describe.**
I was wondering if your component would also work for the BASE TV box? BASE is also part of Telenet and i'm thinking of switching to that provider. [Link to BASE TV-box](https://www.prd.base.be/nl/support/tv/installatie-activering/mijn-base-tv-box-installeren/
)

**Comment by Sholofly** [comment]
Although I can't promise it to you, I'm almost certain that it will work.  I have exactly the same piece of hardware. If you decide to go for Telenet,  please let me know!

**Comment by Nicoautoxp** [comment]
> Although I can't promise it to you, I'm almost certain that it will work. I have exactly the same piece of hardware. If you decide to go for Telenet, please let me know!

Thanks for the reply. I'll let you know if it works with BASE!

**Comment by Nicoautoxp** [comment]
Hi @Sholofly ,
I switched to BASE yesterday and tried to connect using my login, but it doesn't connect. 
Is there a way you could update the integration to include BASE? Or could i change something myself to test it out? I could assist you with any additional info if you would need it.

The error i'm getting is the following:

`Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.12/site-packages/backoff/_common.py:120
First occurred: 30 July 2024 at 02:18:39 (34 occurrences)
Last logged: 22:28:40

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-be.gnp.cloud.telenet.tv/eng/web/recording-service/customers/DTV4308730_be/quota. Error:401 Client Error: Unauthorized for url: https://spark-prod-be.gnp.cloud.telenet.tv/eng/web/recording-service/customers/DTV4308730_be/quota)
Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)`

which seems a logical error as it should maybe be base.tv instead of telenet.tv.
To watch TV online via BASE  we can go to the following address https://www.base.tv , wich is similar to that of telenet.

**Comment by Nicoautoxp** [comment]
@Sholofly would you think it would be possible to add support for BASE?

**Comment by Sholofly** [comment]
Only if i have a login, or someone would add it form to my python project.

**Comment by Sholofly** [comment]
Please upatte and login using the refresh token method for BASE TV...

**Comment by Nicoautoxp** [comment]
@Sholofly its working perfectly, thank you so much for adding it! The only thing that I can't find is a way to start the netflix app. But think i can find just program a button combination for it.

**Comment by Sholofly** [comment]
Do you have a channel for it?

**Comment by Nicoautoxp** [comment]
its not a specific channel, but a seperate app. I looked through the channel list and its not there. I also can't find it anywhere on the web page. Probably because they want you to go to the official netflix app for it. So it fine for me like how it is. Thank you!
