### ISSUE TITLE
Virgin Media UK- Unable to Connect

### ISSUE THREAD

**Issue by Lofty1988** [Sholofly/lghorizon#122]
**Describe the bug**
Currently not able to utilise the plugin for Virgin Media UK

**To Reproduce**
Attempt to login with Virgin Media GB account. Spinning wheel for a few mins & ultimately fails.

**Comment by ColinRobbins** [comment]
I am seeing the same issue - having just done the VIrgin "forced upgrade" to Virgin 360.

I've installed the integration, enter the prover (virgin GB), username and password.   However the config screen just sits there with a spinning wheel.

Happy to provide logs etc, but would need guidance on how to configure HA to get the required info.

**Comment by ColinRobbins** [comment]
Seem to be same issue as https://github.com/Sholofly/lghorizon/issues/82.
Reading the thread, it seems Virgin have changed the authentication mechanism, and no one has found a way around it yet.

**Comment by ColinRobbins** [comment]
Will be fixed by https://github.com/Sholofly/lghorizon/issues/82 solution.   @Sholofly I suggest this issue is closed.

**Comment by Sholofly** [comment]
Check, thanks!
