### ISSUE TITLE
Can not add Ziggo Next mini. 2 factor authentication does not work

### ISSUE THREAD

**Issue by rilitiky** [Sholofly/lghorizon#124]
**Describe the bug**
After adding 2 factor authentication to the Ziggo account (by sms) the Next mini can not be added to Home Assistant. There will be no popup to enter the MFA code.
2FA can not be disabled after enabling it in the Ziggo account.
Unknown error occured

**To Reproduce**

**Expected behavior**
After entering credentials I would expect an SMS and a popup to add the code. Both do not appear.

**Screenshots**

**Version of the component**
0.5.10

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by Sholofly** [comment]
@rilitiky i'll try to look in to this the coming weeks. I hope I can implement this mechanism...

**Comment by Sholofly** [comment]
Where do you get the popup? I can't see where to enable 2fa in ziggogo...

**Comment by rilitiky** [comment]
I'm sorry, I forgot to update this issue.  It was a problem on Ziggo's side. After activating 2FA I needed to reset the password for Ziggo in order to get it to work. Thank you for your effort.
