### ISSUE TITLE
TypeError: LGHorizonApi.__init__() takes from 3 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by dynasticorpheus** [Sholofly/lghorizon#130]
**Describe the bug**
```
Error setting up entry xyz@gmail.com for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    api = LGHorizonApi(
          ^^^^^^^^^^^^^
TypeError: LGHorizonApi.__init__() takes from 3 to 5 positional arguments but 6 were given

```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version of the component**
v0.6.0

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by ColinRobbins** [comment]
That looks like the HA Component has updated, but not pulled the updated library through.

Check that `custom_components/lghorizon/manifest.json` has the line:

```
  "requirements": [
    "lghorizon>=0.7.0"
  ],
```

**Comment by Sholofly** [comment]
> That looks like the HA Component has updated, but not pulled the updated library through.
> 
> Check that `custom_components/lghorizon/manifest.json` has the line:
> 
> ```
>   "requirements": [
>     "lghorizon>=0.7.0"
>   ],
> ```
Yes, that can't be an integration issue since that part is the same for all users...
Please contact me on Discord if you need help with this.

**Comment by dynasticorpheus** [comment]
@Sholofly  I force updated to latest lib but I am afraid I still get this error?  Please note you updated lib version in manifest but not component version itself (e.g. 6.0 --> 6.1)

```
ca37cc9361bd:/config# uv pip freeze | grep lghorizon
lghorizon==0.7.1
```
```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    api = LGHorizonApi(
          ^^^^^^^^^^^^^
TypeError: LGHorizonApi.__init__() takes from 3 to 5 positional arguments but 6 were given
```

**Comment by Sholofly** [comment]
Can you post the line in your code of the __init__ py?

**Comment by ColinRobbins** [comment]
For whatever reason, I am certain this is because the old library is being called.
The modification to the library added 6th argument to support the extra parameter needed.
