### ISSUE TITLE
Too many channels Ziggo NL possibly affecting HomeKit performance

### ISSUE THREAD

**Issue by rjblake** [Sholofly/lghorizon#135]
**Describe the bug**
I added the integration and everything works great in HA. However, If I add as a HomeKit Bridge and add to HomeKit, it seems to cause a massive delay for all my dimmer switches and lights. I've reset Apple Home and recreated from scratch, adding devices/bridges one by one. When I add Ziggo to a bridge, everything almost stops responding if controlled through the Home app on iPhone. 

Is there any way to limit the channels being added to the integration?

**To Reproduce**
Add integration
Add a HomeKit bridge
Add media_player.ziggo 
Scan code and add to HomeKit

**Expected behavior**
Does not impact performance of HomeKit (Home app)

**Screenshots**
n/a

**Version of the component**
0.6.2 (same with earlier versions)

**Logging**
Logger: homeassistant.components.homekit.type_remotes
Source: components/homekit/type_remotes.py:107
integration: HomeKit Bridge ([documentation](https://www.home-assistant.io/integrations/homekit), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+homekit%22))
First occurred: 12:17:24 PM (1 occurrences)
Last logged: 12:17:24 PM

media_player.ziggo: Reached maximum number of sources (90)

**Additional context**
Have currently removed to restore HomeKit performance. However, log messages seem to indicate too many sources as well (not sure if this is related). Also, not sure if the power state (max power saving) of the Ziggo Box has an impact on this (have yet to test)

**Comment by ColinRobbins** [comment]
It would be nice to be able to configure the list of channels in some way.

In a similar scenario, the Phillips Hue integration presents a full list of options (scenes) at the config screen with tick boxes.   It then ignores the ones ticked.

You would have to re-run the config occasionally to re-sync the channel names, as they change over time.

**Comment by ColinRobbins** [comment]
Another option is to use a Media Player Template, deriving all the values for the Ziggo, and expose the template to Homekit.
You can then exclude the sources from the template, side-stepping the issue.

https://github.com/Sennevds/media_player.template

**Comment by Sholofly** [comment]
Although I understand the request I'm not planning to implement this. There are hunderds of channels to choose from, which is too much for the initial config screen. 

But... the LG Horizon platforms knows profiles where you can select channels. See https://github.com/jsiegenthaler/homebridge-eosstb. Probably someone would take a try implementing profile support?

**Comment by Sholofly** [comment]
I'm already working on it :) see personalization branch

**Comment by Sholofly** [comment]
hi @rjblake please update the integration. You're able to generate a new profile on your box with the desired channels in your favorite channels. Then remove and re-add the integration. Select the created profile and you should be good to go....
Please report your findings!

**Comment by rjblake** [comment]
@Sholofly - many thanks for the update. I created a new profile with only 4 channels. After removing and adding the integration back, I added it again as an accessory in HomeKit. Soon after adding, I noticed the same behaviour with my light dimmers - all started responding very slowly to being controlled using the Home app on my iPhone. I will try the following and report back:

1. Change the Standby power profile of the Ziggo Box so as not to use the Eco Mode
2. Try the homebridge plugin (as mentioned in your post above) to see if this works any better, but not sure if working with Ziggo as mentioned by jsiegenthaler on his main page.

Question on the device. Any reason that you've chosen to display the Set-top Box as a TV and not as STB or is this a Home Assistant limitation?

**Comment by Sholofly** [comment]
Thanks @rjblake , why it is slow on homekit then..

About the stb... the HA media_player knows three device classes: tv, speaker, receiver. Tv is the closest one I think.

**Comment by rjblake** [comment]
Have just tried all options. As soon as I add the Ziggo box to HomeKit on my iPhone, everything else slows down to being unusable. This also applies to the Homebridge plug-in. I'm at a loss to understand why this is the case and only seems related to this Ziggo media device

**Comment by Sholofly** [comment]
Strange, since i don't use homekit i can't help you. Only if you're able to find out why it's slowing down, I can look for a fix...
