### ISSUE TITLE
Sunrise / UPC (CH) - Multiple Account Error

### ISSUE THREAD

**Issue by marcob82** [Sholofly/lghorizon#138]
**Describe the bug**
When using Sunrise (CH) Account with multiple subscriptions, Login is not possible. "Unknown error occurred".

**To Reproduce**
1. Go to "Settings" -> "Devices & Services" -> "Add Integration" -> "LG Horizon"
2. Select "UPC Switzerland" Provider and enter Account details.
3. Click "Submit" 
4. Wait for error to show up (screenshot)

**Expected behavior**
Configuration with Multi-Subscription Accounts without error.

**Screenshots**
![lghorizon_error](https://github.com/user-attachments/assets/9b66f236-ade1-42f0-9c70-cd276c8d40ee)

**Version of the component**
v0.6.2

**Logging**
[lghorizon_log.txt](https://github.com/user-attachments/files/17463247/lghorizon_log.txt)

**Comment by t0msen76** [comment]
Same Issue here. I am sure i use the correct username and PW, but even if you enter invalid credentials, the errormessage is the same :-) so i think there is an issue with the authentication process anywhere

**Comment by Sholofly** [comment]
If someone is willing to shared credentials I can give it a try. If so, contact me on discord!

**Comment by Sholofly** [comment]
Fixed by using the new login method. Update to latest and see the docs.
