### ISSUE TITLE
Virgin 360 box unavailable

### ISSUE THREAD

**Issue by woody166** [Sholofly/lghorizon#149]
Hi,

Not sure if this is the right place for this but I am having an issue where my TV Box is constantly becoming unavailable. 

If the box is on then it work fine but as soon as I put it in standby it becomes unavailable in the app and I have to use the remote to take it out off sleep. If this is the normal and expected behaviour then please forgive me.

It would be nice though to be able to activate the tv box when starting a scene or having Alex run a script.

I am at all the latest revision levels for HA and the app.

**Comment by Sholofly** [comment]
What energy mode is your box running?

**Comment by woody166** [comment]
I'm using Active Start

**Comment by mpsamuels** [comment]
I changed my box 'Fast Start' and that seemed to solve this problem.

**Comment by woody166** [comment]
Hi Martin,

Many thanks, I have changed mine to that as well now and seems to be working at the moment 👍🏼

Hopefully sometime in the future there can be some changes made to enable the more energy friendly options 😁
