### ISSUE TITLE
Connection to Telenet broken

### ISSUE THREAD

**Issue by TekFan** [Sholofly/lghorizon#150]
Since this afternoon the integration cannot connect to Telenet anymore

I get this in the log:
Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)

I was running the latest version (0.7.3) and I uninstalled and reinstalled everything but to no avail.
I even tried a previous version (0.6.2), but no cigar.

Now, it may be just a coincidence but this just happened after having changed my subscription to a OneUp to get 1Gbit internet.
Other than that nothing changed, still exactly the same credentials, etc.
My TV-Box is working fine as well as the app on my mobiles, I can even remote control my TV-Box from the app so there doesn't seem to be a server outage.

I uninstalled the integration thinking that there could be an old token stored somewhere, but now I can't even install it back anymore as it doesn't pass the initial authentification.

Is there anything else I could try ?

**Comment by denandy83** [comment]
It’s not you. It broke for me too 2 days ago
I get ‘This entity is no longer being provided by the lghorizon integration‘ when I tap on it

**Comment by Sholofly** [comment]
Please update to the latest version and reauthenticate using the Refresh token method. Please let me know if that works for you.

**Comment by denandy83** [comment]
Works again after update, didn’t need to update token

**Comment by GlennLenaerts** [comment]
> Please update to the latest version and reauthenticate using the Refresh token method. Please let me know if that works for you.

How di reauthenticate? how do i do the refresh token method?

**Comment by Sholofly** [comment]
Remove the current integration en readd it..

**Comment by GlennLenaerts** [comment]
iff i want to add it ask a token is that the same as the password?

**Comment by ColinRobbins** [comment]
How to get the token is described in the Readme: 
https://github.com/Sholofly/lghorizon?tab=readme-ov-file#configuration-for-virgingb-sunrise-ch-telenet-be-and-base-be

**Comment by GlennLenaerts** [comment]
it worked thankx mate

**Comment by bedar89** [comment]
Sorry to open this issue, please let me know if you want me to start a new issue.

I'm unable to obtain a token from Telenet. No matter on what page I look (my telenet, telenet.tv, etc) I never seem to get any token. I've used both Chrome and Edge with the provided extensions.

@GlennLenaerts, how did you obtain your token with Telenet?

**Comment by GlennLenaerts** [comment]
I used firefox an followed the tutorial on the page

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GlennLenaerts** [comment]
You must sign in into telenet tv online in firefox first

**Comment by TekFan** [comment]
Forgot to update...
Yes, this worked for me as well, thanks !

Sidenote: Do not unlog in Firefox once you have extracted the token, I learned the hard way that it invalidates the token and the integration will fail at the next HA restart.
