### ISSUE TITLE
Telenet no longer working since last update

### ISSUE THREAD

**Issue by jonasv05** [Sholofly/lghorizon#156]
**Describe the bug**
Telenet no longer working since last update
Devices are not accessible anymore
Cannot reconfigure the integration (re-add provider telenet with username, no password is asked, dtv-code entered without refreshtoken --> unable to connect)

**Expected behavior**
Able to add the account and select my dtv-boxes as before

**Version of the component**
Latest

**Logging**
```
Deze fout is ontstaan door een aangepaste integratie.


Logger: custom_components.lghorizon.config_flow
Bron: custom_components/lghorizon/config_flow.py:203
integratie: LG Horizon (documentatie, problemen)
Eerst voorgekomen: 11:04:27 (1 gebeurtenissen)
Laatst gelogd: 11:04:27

can only concatenate str (not "NoneType") to str
```

PS: DTVcode for telenet can be found in MyTelenet > MyProducts > TV > Summary of your decoders (might be a more user friendly approach)

**Comment by Sholofly** [comment]
Did you try to reconfigure the integration, using the refresh token?

**Comment by simjogit** [comment]
A stupid question maybe, but where do I find the refresh token for Telenet? I tried with JWT inspector but without success.

**Comment by jonasv05** [comment]
> A stupid question maybe, but where do I find the refresh token for Telenet? I tried with JWT inspector but without success.

I'm afraid i do not know either. Can't find it in the readme either.

**Comment by ColinRobbins** [comment]
Try using Firefox as per the instructions here:  
https://github.com/Sholofly/lghorizon?tab=readme-ov-file#configuration-for-virgingb-sunrise-ch-telenet-be-and-base-be
It seems a more reliable approach to getting the token than Chrome or Edge.

@Sholofly if may be worth dropping Chrome and Edge from the Readme - or strongly recommending Firefox.

**Comment by Hisedase** [comment]
Same Here, not working anymore, cannot connect

**Comment by Sholofly** [comment]
@Hisedase Tried the refresh token method?

**Comment by Hisedase** [comment]
Gonna try today

**Comment by Hisedase** [comment]
It works ! Thx man !

**Comment by simjogit** [comment]
It works indeed. Thx!

**Comment by jonasv05** [comment]
> Try using Firefox as per the instructions here: https://github.com/Sholofly/lghorizon?tab=readme-ov-file#configuration-for-virgingb-sunrise-ch-telenet-be-and-base-be It seems a more reliable approach to getting the token than Chrome or Edge.
> 
> @Sholofly if may be worth dropping Chrome and Edge from the Readme - or strongly recommending Firefox.

worked like a charm, thq!!!

**Comment by Novan007** [comment]
TELENETTVBOX 1 no longer available. i have deleted the lg horizon en re installed with the token but the problem keep the same. Can You help me?
