### ISSUE TITLE
Telenet box no longer available

### ISSUE THREAD

**Issue by Novan007** [Sholofly/lghorizon#159]
Telenetbox no longer available. I have deleted the tv horizon and reinstalled with the refresh token and the problem is the same. How can i make the telebox work again?

**Comment by Novan007** [comment]
Oké Found it's because the box was on eco standby.
This case van be closed

**Comment by Bryn72** [comment]
Can someone tell me how to install this integration for Telenet? It used to work, but since the last update, the configuration method has changed (refresh token?) and I’m stuck… Thank you!
