### ISSUE TITLE
Telenet refresh token expires / changes?

### ISSUE THREAD

**Issue by darkpainy** [Sholofly/lghorizon#162]
Hi,

I set up the integration with the refresh token, after a reboot of HA i noticed that my integration stopped working.
I tried to set it up again using the refresh token I had saved from the first time, but with no success.
I then checked again with firefox and I now have a different refresh token, which works again.
But does this mean the token changes from time to time? Or is it only valid for one login?

Kind regards,
Jeroen

**Comment by ColinRobbins** [comment]
The refresh token is regularly updated in the background.
The new token should be automatically stored in HA and used after a restart.
I’ve been running for over a month now, with no-need to re-supply the token.

Perhaps…. Once you have the token captured from Firefox, close the browser window (without logging out). It’s possible the session in Firefox is doing some kind of auto logout, which will affect the HA session (we are in effect performing a session hijack).

**Comment by darkpainy** [comment]
I'll try that :)

**Comment by darkpainy** [comment]
It seems after 1 day (or less?) my token expires and is not refreshed.
I closed the Firefox window without logging out as sugested, the next day my integration shows the same error.

**Comment by ColinRobbins** [comment]
Thats odd.  I'd maybe Telenet is behaving differently to VIrgin in the UK.
Can you turn the debug logs on.
Then look for messages along the lines of  `New JWT stored`.
You should see one such message when you restart HA.
If you leave HA running, you should also see such messages when you box has been switch off for a few hours, and is switched back on.
This may give a clue as to what is happening.

**Comment by ColinRobbins** [comment]
To turn the debug logs on you need the following added to your config:
```
logger:
  logs:
    lghorizon: debug
    custom_components.lghorizon: debug
```

**Comment by darkpainy** [comment]
I've enabled debug logging, restarted HA.
integration still working
Currently only seeing 
2024-11-20 23:43:57.900 DEBUG (Thread-13 (_thread_main)) [lghorizon.models] Sending PINGREQ
2024-11-20 23:43:57.936 DEBUG (Thread-13 (_thread_main)) [lghorizon.models] Received PINGRESP

will let you know tomorrow if anything changes

**Comment by darkpainy** [comment]
tried again, has not expired in the past 3 days... so  hopeing it will keep on working :)
