### ISSUE TITLE
possible to open radio app on telenet tv box?

### ISSUE THREAD

**Issue by fredjethehulk** [Sholofly/lghorizon#163]
Hi,

I am wondering if it is possible to open the radio app and play a certain radio station.
I can choose sources (that are my tv channels to watch).
And i can also my recording in in browser media.
Problem is that de radio channel a app is on the telenet tv box and i don't find the app in my HA.
I think it is possible because the Netflix app is among the sources.
The only thing is if i look at the telenet.tv web page i don't see the radio app in between it but also the netflix app isn't also on the list, but it is visible (netflix app) in the source list at HA.

thanks in advance for the help
![sources](https://github.com/user-attachments/assets/15aa9347-01be-4d9a-a03f-690f7e6880a9)

![opnames](https://github.com/user-attachments/assets/876f884a-e6fa-498f-9aa0-007aedd883c0)

**Comment by Sholofly** [comment]
Unfortunately i didn't find a way to do that. If there's a way to accomplish that using the web interface in your browser, there's a way to do it in my component.
