### ISSUE TITLE
LG Horizon Integration - Error "Cannot Connect" Despite Correct Credentials

### ISSUE THREAD

**Issue by Bart-Roels** [Sholofly/lghorizon#164]
Hi everyone,

I’m trying to set up the LG Horizon integration in Home Assistant and have managed to find both the refresh token and the DTV identifier. However, every time I enter these credentials, I keep getting the error "Cannot connect."

I’ve double-checked the values, and I’m confident they are correct. I’m also using the latest version of the plugin.

Has anyone else encountered this issue or have an idea how to resolve it? Any advice would be greatly appreciated!

Thanks in advance!

![image](https://github.com/user-attachments/assets/54598242-1ba7-4567-ba13-1bbb587ff975)

![image](https://github.com/user-attachments/assets/70df47c9-f525-4958-88f1-9fbeea1c41b2)

**Comment by axelsegers** [comment]
Same here (using Telenet)

**Comment by StevenBrs** [comment]
Here also
Telenet; cannot connect
Possibly since update from HA2024.10 to 2024.11.3

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 64, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError
```

**Comment by filip-heens** [comment]
Same Here, after doing the latest update and reboot, my 2 Telenet Decoders are no longer found

**Comment by vrankbakkes** [comment]
same here

**Comment by Sholofly** [comment]
Did you try reading the integration and using the refresh token login? See docs for instructions.

**Comment by vrankbakkes** [comment]
I have removed LG Horizon integrations and done a new integration and now it works again after the update 2024.12.1 .

**Comment by vrankbakkes** [comment]
> Did you try reading the integration and using the refresh token login? See docs for instructions.

before update 2024.12.1 it worked great after update the 2 tv boxes were no longer accessible. Now I have removed the integrations and again and now it works super well again

**Comment by Sholofly** [comment]
Yeah sorry, my change wasn't backwars compatible, due to changes at LG... Good to hear it works.

**Comment by filip-heens** [comment]
Sorry, missed the change... it's working again here also. Had to delete the integration and re-add it though... isn't there a way to re-add the refresh token without deleting and re-adding the integration?

**Comment by StevenBrs** [comment]
Sorry I'm gonna be the party pooper, but for me it isn't solved yet. (For Belgium/Telenet)

After a lot of debugging I found out the problem is most likely different devices and IPv6:
My HA is running on a NAS, which has IPv6 support, and I was requesting the Refresh Token from my Win11 PC, also IPv6.
This didn't match very well... After disabling IPv6 on the NAS and spinning up a VM, I could authenticate and add the LG Horizon integration in that same webbrowser, running on the same machine as Home Assistant. 
(Probably disabling IPv6 wasn't necessary...)

Looking at the code I was wondering: Isn't it possible to fetch the refresh token automatically with the username & password ?
Would be easier in above case, and also, I had to install Firefox only to configure this integration :-)

**Comment by ColinRobbins** [comment]
> Looking at the code I was wondering: Isn't it possible to fetch the refresh token automatically with the username & password ? Would be easier in above case, and also, I had to install Firefox only to configure this integration :-)

The code did originally work using username and password, and getting the required tokens.  However, Virgin changed their backend and the code stopped working.   (In the UK) this was traced to Virgin implementing an additional authentication step using a Captcha.
Sadly the Home Assistant configuration approach is unable to deal with Captchas, as it requires user interaction via a browser.

So yes, it would be possible to get the token via username and password, but you'd still have the Captcha to deal with.
To get the Captcha cookies, you'd have to fire up a browser, log on, solve the Captcha then copy the cookies into HA.   This would be just as cumbersome as getting the refresh token for the user, and require more complex code in the integration.
(Note the Captcha may run in the background so you may not see it on screen when login into Virgin)

For an example of an integration that grabs cookies see https://www.home-assistant.io/integrations/google_maps/, and you'll see it similarly difficult to configure.   This suffers the same issue - every now and again it fails, and you have to repeat the cookie grab

What is needs to for someone to talk to Virgin and get them to implement OATH2 properly - as per many HA integrations.

**Comment by XalaTheShepard** [comment]
For the people using Telenet, what was the solution? I always get the message 'cannot connect'. Also when using the JWT debugger in Firefox I get the message 'Invalid signature'. Thanks for the support. Kind regards, Robin

**Comment by Bart-Roels** [comment]
> For the people using Telenet, what was the solution? I always get the message 'cannot connect'. Also when using the JWT debugger in Firefox I get the message 'Invalid signature'. Thanks for the support. Kind regards, Robin

Jup stil got the same problem Here

**Comment by Bart-Roels** [comment]
> Sorry I'm gonna be the party pooper, but for me it isn't solved yet. (For Belgium/Telenet)
> 
> 
> 
> After a lot of debugging I found out the problem is most likely different devices and IPv6:
> 
> My HA is running on a NAS, which has IPv6 support, and I was requesting the Refresh Token from my Win11 PC, also IPv6.
> 
> This didn't match very well... After disabling IPv6 on the NAS and spinning up a VM, I could authenticate and add the LG Horizon integration in that same webbrowser, running on the same machine as Home Assistant. 
> 
> (Probably disabling IPv6 wasn't necessary...)
> 
> 
> 
> Looking at the code I was wondering: Isn't it possible to fetch the refresh token automatically with the username & password ?
> 
> Would be easier in above case, and also, I had to install Firefox only to configure this integration :-)


So do you have any idea how I can solve this when running HA on a raspberry pi? Because unfortunately I don't have a production ready machine that I can run vms on. The nice thing about raspberry pi is that it doesn't use a lot of power.

**Comment by axelsegers** [comment]
> For the people using Telenet, what was the solution? I always get the message 'cannot connect'. Also when using the JWT debugger in Firefox I get the message 'Invalid signature'. Thanks for the support. Kind regards, Robin

For Telenet it works here with the JWT token

**Comment by Bart-Roels** [comment]
> > For the people using Telenet, what was the solution? I always get the message 'cannot connect'. Also when using the JWT debugger in Firefox I get the message 'Invalid signature'. Thanks for the support. Kind regards, Robin
> 
> 
> 
> For Telenet it works here with the JWT token

And what is your setup for HA? So you need the refresg Token from the decoded part huh like in my screenshot? Because every time I try that I get error

**Comment by vrankbakkes** [comment]
> > > For the people using Telenet, what was the solution? I always get the message 'cannot connect'. Also when using the JWT debugger in Firefox I get the message 'Invalid signature'. Thanks for the support. Kind regards, Robin
> > 
> > 
> > For Telenet it works here with the JWT token
> 
> And what is your setup for HA? So you need the refresg Token from the decoded part huh like in my screenshot? Because every time I try that I get error

not the decoded part but the encoded that on the left side i think

**Comment by axelsegers** [comment]
Indeed the encoded part on the left

**Comment by XalaTheShepard** [comment]
Thanks everyone. With the encoded part of the JWT debugger, I was able to set the integration up for Telenet.

**Comment by HamsenBender** [comment]
Waaww, that's it, you have to use the encoded part....
Tx!

**Comment by Bart-Roels** [comment]
My issue was related to certain services not functioning correctly on my Raspberry Pi due to IPv6 communication. After troubleshooting, I resolved the problem by disabling IPv6 entirely and configuring the system to use IPv4 only.

For anyone encountering similar challenges, consider checking your IPv6 configuration as a potential root cause.
