### ISSUE TITLE
Integration not showing up in HACS

### ISSUE THREAD

**Issue by stingone** [Sholofly/lghorizon#2]
Just copied al the files to my custom_components/lghorizon directory. no matter what i do its not showing up in the integrations page.

**Comment by Sholofly** [comment]
Please reboot and clear browser cache. Search for LG Horizon!

**Comment by Sholofly** [comment]
For the record: Your title says it's not showing up in HACS. That's correct, it's not available there yet. Your message states you're looking in the integrations page: There it should be.

**Comment by pvmil** [comment]
Very nice to have an integration supporint the Ziggo next box.
Do you have a timeline on adding this to HACS?

**Comment by Sholofly** [comment]
Hi @pvmil , Thanks. It was available before but then Liberty Global decided to change their backend.
For know I haven't decided yet. There are some minor issues I want to solve and features I want to add, but I am limited in my time ATM.

**Comment by Jordenjj** [comment]
It can easily be used with hacs. Just add the git repo to custom repositories in hacs. You'll get updates and everything like you're used to and no folder copying.

**Comment by Sholofly** [comment]
@Jordenjj, Thanks! I know how it works, but i feel my integration is not ready for that step yet.

**Comment by Jordenjj** [comment]
I understand. From my testing however, it works like a charm. 

Thank you for your work on this, its great.

**Comment by Sholofly** [comment]
Thanks @Jordenjj if you see any improvements or bugs, don't hesitate to submit an issue!
