### ISSUE TITLE
Virgin Media (GB) didn't connect without a value in identifier field

### ISSUE THREAD

**Issue by callumeveratt** [Sholofly/lghorizon#30]
The documentation appears to say that the identifier field is not required unless using Telenet.

I'm just moving from the old Arris integration and when I tried to add originally I saw this error in HA:

> Logger: custom_components.lghorizon.config_flow
Source: custom_components/lghorizon/config_flow.py:78
Integration: LG Horizon ([documentation](https://github.com/Sholofly/lghorizon), [issues](https://github.com/Sholofly/lghorizon/issues))
First occurred: 10:36:38 (3 occurrences)
Last logged: 10:36:55
 'indentifier'

I went back and added the integration but put 'no' in the identifier field (just as a test) and the integration added and it all works. So not sure if the config flow expects a value for identifier?

**Comment by Sholofly** [comment]
@callumeveratt What version did you install?

**Comment by callumeveratt** [comment]
Literally just installed it so grabbed the most recent at the time - [v0.3.10](https://github.com/Sholofly/lghorizon/releases/tag/v0.3.10)

**Comment by Sholofly** [comment]
Think it's abut a typo on my side. I'll fix it rightaway
