### ISSUE TITLE
Unable to connect VM (GB)

### ISSUE THREAD

**Issue by Rappoman** [Sholofly/lghorizon#35]
I was using arris_dcx960 integration until a few days ago.  I managed to install this (latest version) integration and it was working to some degree.  I noticed that the source list was not showing correctly.  I thought I may have configured incorrectly, so I tried installing again.  Since then I have been unable to connect.  I am using the correct username and password (reset password to make sure).  I have tried earlier releases of this integration  but none seem to work for me.

Logs show:

This error originated from a custom integration.

Logger: custom_components.lghorizon.config_flow
Source: custom_components/lghorizon/config_flow.py:81
Integration: LG Horizon (documentation, issues)
First occurred: 22:28:19 (2 occurrences)
Last logged: 22:31:31

'LGHorizonAuth' object has no attribute 'accessToken'

My HA instance is running latest versions.

**Comment by Sholofly** [comment]
Hi @Rappoman Thank you for reporting  your issue. Please let me know, are you able to login into the web interface of your VM TV website?

**Comment by Rappoman** [comment]
Hi @Sholofly, I can sign in to my account via the Web interface.  In order to do so I had to remove the device authentication (biometrics).  After which I have just tried to setup the integration again  and it has worked.  

Thanks for your time to reply and to create this integration.

**Comment by Sholofly** [comment]
Hi @Rappoman! Merry Christmas to you! I can't pass the biometric challenge so to use my component you did the only thing possible, disable it. Have nice Holidays!

**Comment by Rappoman** [comment]
@Sholofly Merry Christmas to you too.
