### ISSUE TITLE
Google home

### ISSUE THREAD

**Issue by Pafi2021** [Sholofly/lghorizon#39]
The mediabox doens't show up anymore in the google home app also its not posible to controle the box true google assistant

**Comment by Sholofly** [comment]
Hi @Pafi2021 , Please let me know if HA is working properly. If so it isn't a HA probem I guess...

**Comment by Pafi2021** [comment]
i did a complete reinstall of HA with only this intergration google home still can't find anything google home compatible

**Comment by Sholofly** [comment]
How do you connect to GH? using Nabu Casa?

**Comment by Pafi2021** [comment]
Yes HS is connect true Nabu Casa to Google home

**Comment by Sholofly** [comment]
@Pafi2021 Are you sure you've exposed it to Google Assistant in your cloud page?

**Comment by Pafi2021** [comment]
Yes im sure it was working perfectly for the last year of so ans suddenly it stopped working for me

**Comment by Sholofly** [comment]
@Pafi2021 I'm doubting it's my component's issue. Mine works quite fine in the Google Home and I did not receive other issues. Can you try to decouple and try to add it again?

**Comment by jrspowers** [comment]
Hello, I can also perfectly operate my Telenet TV box via Google Home, so there is certainly no problem on your part @Sholofly @Pafi2021

**Comment by jrspowers** [comment]
Here picture in Google home ![image](https://user-images.githubusercontent.com/60328474/224074928-935f211d-629f-4945-a9fe-6f3ed5119545.png)
