### ISSUE TITLE
LG Horizon lghorizon.remote_key service/ option not working anymore

### ISSUE THREAD

**Issue by canedje** [Sholofly/lghorizon#42]
**Describe the bug**
This evening LG Horizon Integration was not working anymore.
After reload the integration it is partly working again.
Only remote_key function does not work anymore. I did use that for selecting a channel in NodeRed.: {"remote_key":"2"}
Now I use the  {"media_content_id":"1","media_content_type":"channel"} option in NodeRed. This is still working
It looks like that lghorizon service is not working anymore. Service media_player is still working
EDIT: I also tried remote_key.Channel up. Thats also not working

**To Reproduce**
1. Use NodeRed automatiom remote_key channel 1
2. Nothing happens.'

**Expected behavior**
Switching to the chosen channel

**Screenshots**
![image](https://user-images.githubusercontent.com/23150947/215578774-346f15ec-cdf6-40b8-a05b-abbe59383fa2.png)
is not working anymore. It did before
![image](https://user-images.githubusercontent.com/23150947/215578924-ba36a4d2-e2ab-4dba-809d-7dbaae5efc8b.png)
Is working as alternative option

**Version of the component**
The version of the component as it is installed on your HA

**Logging**
No logging information
```

**Additional context**

**Comment by canedje** [comment]
I just did restart HA.
Now all is working again???
A hick-up?
This issue can be closed

**Comment by Sholofly** [comment]
Thanks for the message. Have you checked the logs? Maybe there was an issue.

**Comment by canedje** [comment]
@Sholofly : I like to do a new comment on this one.
Today again not workingg service of LGHorizon.
Both situation (this time and the one mentioned over here before) did start after a while no connection to internet (update of my UDM Pro router)
After reconnect to Internet and restart HA everything is working again.
Can it be caused by temporary no connection to internet?
