### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by JATD2020** [Sholofly/lghorizon#48]
Is it possible to make YouTube available in the channel select dropdown? Netflix/Videoland/Disney and others are available, but I'm not able to select YouTube.

**Comment by Sholofly** [comment]
Hi @dof250 Only when youtube is available on one of your regular channel numbers. Is that the case?

**Comment by JATD2020** [comment]
Just checked, it isn’t available as a regular channel number so too bad… thanks for the quick reply!
