### ISSUE TITLE
Integration called deprecated "async_setup_platforms" instead of awaiting "async_forward_entry_setups"

### ISSUE THREAD

**Issue by medivb** [Sholofly/lghorizon#49]
**Describe the bug**
Warning message of deprecated function when starting integration:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for lghorizon using this method at custom_components/lghorizon/__init__.py, line 49: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**To Reproduce**
Start integration on HA instance with version 2023.2.xx

**Expected behavior**
No warning about deprecated function use and that integration will continue to work in HA 2023.3

**Screenshots**
n/a

**Version of the component**
0109318

**Logging**
n/a

**Additional context**
n/a

**Comment by Sholofly** [comment]
Hi @medivb, This is already fixed in the latest version.
