### ISSUE TITLE
Not showing up in hacs

### ISSUE THREAD

**Issue by Fifke** [Sholofly/lghorizon#5]
The integration is not showing up in hacs.
Even after deleting cache , etc... Not showing up. Is it already available?

**Comment by Sholofly** [comment]
Yes, but you need to add my GitHub repository as custom. It's not in the
default repo yet

Op wo 26 okt. 2022 20:49 schreef Fifke ***@***.***>:

**Comment by Fifke** [comment]
Ok. Thx . Got it set up. This works with Telenet!

**Comment by Sholofly** [comment]
The default HACS repo addition is on his way: https://github.com/hacs/default/pull/1553
