### ISSUE TITLE
playback time views media card

### ISSUE THREAD

**Issue by jrspowers** [Sholofly/lghorizon#50]
**Is your feature request related to a problem? Please describe.**
no problem but new feature request

**Describe the solution you'd like**
I would like to have the function that the playback time of the program is displayed in the media card, as shown in the photo is the case of Sonos Music

Describe alternatives you've considered

at sonos it is called that for the media playback time, I think it is displayed in seconds
```yaml
media_duration: 172
```

**Additional context**
![image](https://user-images.githubusercontent.com/60328474/223115945-cb71e736-9b01-4818-8f74-611d4db8762c.jpeg)

**Comment by Sholofly** [comment]
@jrspowers Can you update to v0.5.0? It adds the progress bar to VOD and recordings. For other play types (regular tv or playback) it isn't supported. Seeking isn't available either.

**Comment by jrspowers** [comment]
Thanks man this work perfect ![image](https://user-images.githubusercontent.com/60328474/224372749-cadd4cf6-8da3-4bf2-8458-f4c294b34624.jpeg)
