### ISSUE TITLE
Show "Pause" status when watching TV

### ISSUE THREAD

**Issue by binoke** [Sholofly/lghorizon#53]
**Is your feature request related to a problem? Please describe.**
When I put my Telenet TV Box on pause watching one of channels. It does not reflect in the app (not in the view or the logs)

**Describe the solution you'd like**
Show the Pause status of TV Channels in the HA media player so it can be used remotely or to trigger items

**Describe alternatives you've considered**
It works when I use a chrome cast on the same TV.   

**Additional context**
![image](https://user-images.githubusercontent.com/30434109/224425817-b28c708f-05e9-4276-a139-68b128aac587.png)

![image](https://user-images.githubusercontent.com/30434109/224425945-cc05a13e-a770-461f-92f8-bcf1bd947bf5.png)

**Comment by Sholofly** [comment]
Hi @binoke , thanks for reaching out. I'm not able to reproduce it. It looks like you're not playing linear tv, are you? It also doesn't refelect the current played media so it looks like it wasn't able to handle the status update from the box. Can you find out it's related to certain channel or something?

**Comment by binoke** [comment]
I have done a bit more testing over the weekend.
I have 2 Telenet TV-boxes.   The one called "beneden" shows the Pause correct.  When I'm watching TV, for example "VTM" and put it on pause, it shows as paused on on the media player status in HA.
When I try that with the second, called "boven" it does not.   
When I put the channel on pause via the media player, it pauses on the Telenet Media Box.  It does that with both.
I will check both TV box configs, as I assume that would be where the problem is.

**Comment by Sholofly** [comment]
Hi @binoke, any update on this matter?
