### ISSUE TITLE
Error: Unable to fetch recording capacity

### ISSUE THREAD

**Issue by sammyke007** [Sholofly/lghorizon#55]
**Describe the bug**

Hi @Sholofly! Still running this great integration and loving it a lot! 
Since a week or two the HASS log's show up the following error. No big problem, just FYI.

```
Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.10/site-packages/lghorizon/lghorizon_api.py:425
First occurred: 1 april 2023 om 15:38:33 (9 occurrences)
Last logged: 07:38:33

Unable to fetch recording capacity...
```

**To Reproduce**
/

**Expected behavior**
/

**Screenshots** 
/

**Version of the component**
v0.5.0

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    arris_dcx960: debug
```

**Additional context**

**Comment by sammyke007** [comment]
Still showing up, any idea?

**Comment by Sholofly** [comment]
Hi sammyke, no, unfortunately not. Do you record in the cloud or on the device?

**Comment by Sholofly** [comment]
BTW you'll have to chage arris_dcx960 to lghorizon to enable logging.

**Comment by sammyke007** [comment]
> Hi sammyke, no, unfortunately not. Do you record in the cloud or on the device?

In the cloud (new TVboxes don't have a HDD anymore). Might be something wrong on their api, but it's only the recording capacity that errors...

**Comment by X1pheR** [comment]
I'm receiving the same error but can actually explain why (at least in my case) it's showing up. I have Ziggo with TV Start subscription. This subscription does not provide recording ability and only 2 days history playback instead of 7 or something days like normal. @sammyke007 are you able to actually record on your mediabox or do you also get a message (as in my case) that you have to upgrade your subscription to enable recording.

**Comment by Sholofly** [comment]
@X1pheR, can you provide me some logging? It would be useful if i can get some logging about your account details (Except for personal info of course) To determine if I am able to disable the recording capacity based on that intel :)

**Comment by X1pheR** [comment]
> @X1pheR, can you provide me some logging? It would be useful if i can get some logging about your account details (Except for personal info of course) To determine if I am able to disable the recording capacity based on that intel :)

Unfortunately I've switched providers so cannot provide any info anymore. Now using an Odido 4K Android TV box.

**Comment by FlexxFR** [comment]
> I'm receiving the same error but can actually explain why (at least in my case) it's showing up. I have Ziggo with TV Start subscription. This subscription does not provide recording ability and only 2 days history playback instead of 7 or something days like normal. @sammyke007 are you able to actually record on your mediabox or do you also get a message (as in my case) that you have to upgrade your subscription to enable recording.

I have the same.
This intergration is working fine, but it would be nice if it could be configured not to check the online services/recording.
Just to keep the logs clean :)

This one probably also related:
Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/recording-service/customers/<XXXXXXX>_nl/quota. Error:402 Client Error: Payment Required for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/recording-service/customers/<XXXXXXX>_nl/quota)

**Comment by ColinRobbins** [comment]
I am seeing this in the UK and too.
I can see the recording data with the Virgin Web interface, so the data should be available.
For some reason this HA option is generating an error accessing it.

Once I’m done fixing https://github.com/Sholofly/lghorizon/issues/82 I’ll take a deeper look at this.

**Comment by Sholofly** [comment]
Sensor should be ignored in this case. LEt me know if this works allright now.

**Comment by ColinRobbins** [comment]
Fixed for GB.
