### ISSUE TITLE
MQTT required ?

### ISSUE THREAD

**Issue by titiviking** [Sholofly/lghorizon#59]
Is MQTT a prerequisite for the integration to work ?
based on debug logs, it looks like all data is being exchanged throught the API's... 

All MQTT interaction seem to be failing (see other bug report https://github.com/Sholofly/lghorizon/issues/58 )
Hence, MQTT does not seem to provide any added value and could/should possibly disabled...

Perhaps some integrations require MQTT to work, but for Telenet that does not seem to be the case. Hence I would rather have the option to disable such connectivity and avoid sharing information to unrelated 3rd party websites.

Curious to get your opinion/feedback.

**Comment by Sholofly** [comment]
The component, at least in NL, is fully depending on mqqtt. The state changes of the box are pushed so other applications, like this, but also the telenet.tv website,  can act on the state changes... If the Belgian component acts otherwise, please let me know.
