### ISSUE TITLE
media info

### ISSUE THREAD

**Issue by Hermanfbe** [Sholofly/lghorizon#6]
**Describe the bug**
Same media info on 2 default cards
Yesterday I tested this add-on; seems to work fine
only problem on this moment:
2 tv-boxes were found: tvbox1 and tvbox2
so 2 cards were created with the correct info
When starting first tv-box everything was ok and I got the media info on the screen (displaying the program that was on TVbox1
After starting tvbox 2 and change the source to another channel, the media info was correct; but after 5 seconds media info on both cards became the same.
Altough I can still change the source on both tvboxes

**Comment by Sholofly** [comment]
Hi @Hermanfbe, what version of my component do you use?

**Comment by Hermanfbe** [comment]
v0.3.0b3; I do see there is a update , will try that tomorrow

**Comment by Sholofly** [comment]
never mind. Found the issue. I am going to fix it!

**Comment by Hermanfbe** [comment]
Thanks for the effort
