### ISSUE TITLE
Use 'voice' button on remote control to generate Home Assistant Assist command

### ISSUE THREAD

**Issue by Foxhill67** [Sholofly/lghorizon#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Wild idea: would it be possible to use the 'voice' button functionality of the remote control to generate an input command for the new Home Assistant Assist feature? 

**Describe alternatives you've considered**
none

**Additional context**
![remote voice button](https://user-images.githubusercontent.com/35631055/236912872-2e8d7ca1-c0af-412d-81e7-4686c92024c4.JPG)

**Comment by Sholofly** [comment]
Nice suggestion! I don't know if i'm able to capture the speech. I won't look at it soon, due to a lack of time. Maybe later.

**Comment by Sholofly** [comment]
@Foxhill67 Did a research on this tonight. There's no possibillity to capture the voice button and the spoken text. Unfortunately this isn't possible ATM.
