### ISSUE TITLE
integrate Sunrise TV (Switzerland)

### ISSUE THREAD

**Issue by steuerzentrale** [Sholofly/lghorizon#64]
@Sholofly  First of all many thanks for this nice piece of software. I live in Switzerland and used UPC for a long time. UPC has been merged into Sunrise in Switzerland and in future every UPC-customer will become a Sunrise-customer (https://www.sunrise.ch/de/home). Basically the set-top box from Sunrise is the same as from UPC. There is also a login (https://www.sunrise.ch/mysunrise) where you can track your devices and services.

Is it possible to extend the support of LG Horizon to Sunrise-customers in Switzerland? I would be willing to help as I recently moved my subscription from UPC to Sunrise and couldnt find any integration to control my set-top box. I am no technical expert but I guess their backend is probably more or less the same as the GUI of the set-top box is identical to the one from UPC.

Regards from Switzerland

**Comment by steuerzentrale** [comment]
@Sholofly not sure if this has been assigned to you, thats why I mention you in this comment

**Comment by Sholofly** [comment]
HaHi @steuerzentrale, Have you tried the UPC Switzerland option? I guess it should work because it already uses sunrise URLs

**Comment by steuerzentrale** [comment]
no I havent, and yes its working! thanks a lot for that hint. its important to know that you have to login with the credentials you may use with the Sunrise TV app, which is not the same as the My Sunrise credentials.
