### ISSUE TITLE
Unable to login (Telenet BE)

### ISSUE THREAD

**Issue by pejeio** [Sholofly/lghorizon#65]
**Describe the bug**
After trying to log in with my Telenet credentials, the submit button keeps spinning.

**Log**

```bash
Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.telenet.tv/eng/web/linear-service/v2/replayEvent/telenet5?returnLinearContent=true&language=nl. Error:404 Client Error: Not Found for url: https://prod.spark.telenet.tv/eng/web/linear-service/v2/replayEvent/telenet5?returnLinearContent=true&language=nl)
```

**Comment by Sholofly** [comment]
Still the same?

**Comment by Dimitry1977** [comment]
I have the same today

**Comment by Sholofly** [comment]
@pejeio, @Dimitry1977 What brand of box do you guys use?

**Comment by Dimitry1977** [comment]
Hey,

I think its Arris DCX-960

See Picture Below

Kind Regards
Collin Dimitry

Rudolf Offereins schreef op 25/10/2023 09:17:

> @pejeio [1], @Dimitry1977 [2] What brand of box do you guys use?
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/pejeio
[2] https://github.com/Dimitry1977
[3] 
https://github.com/Sholofly/lghorizon/issues/65#issuecomment-1778658528
[4]

**Comment by Mjimsas** [comment]
Also having this issue on a clean install running v0.5.1. The box i am using is a Arris DCX-960-MPA+.
Username(email) and password from telenet are correct and have tried with and without the DTV identifier.
The log output from HA shows this: 
ERROR (SyncWorker_4) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://prod.spark.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://prod.spark.telenet.tv/auth-service/v1/mqtt/token)

**Comment by Sholofly** [comment]
Can you show me login screens (with sensitive data obfuscated) you see when you are lgging in on the web environment of Telenet?

**Comment by IngmarG** [comment]
> Can you show me login screens (with sensitive data obfuscated) you see when you are lgging in on the web environment of Telenet?

Doesn't work for me anymore also (since about 6 weeks)
What do you need? Obviously not mijntelenet.be .

**Comment by Mjimsas** [comment]
> Can you show me login screens (with sensitive data obfuscated) you see when you are lgging in on the web environment of Telenet?

Here are some screenshots from the telenet tv login procedure. 
![telenet_01](https://github.com/Sholofly/lghorizon/assets/149004029/8bc9826d-27c0-4917-847f-83d129775f3d)
![telenet_02](https://github.com/Sholofly/lghorizon/assets/149004029/1d44481b-dc46-4310-818f-72125da21479)
![telenet_03](https://github.com/Sholofly/lghorizon/assets/149004029/b7d7058d-433c-42a3-851d-263c44b8ed75)

I'm happy to help if you need something specific/more.

**Comment by Sholofly** [comment]
@Mjimsas Thank you for the screens. It looks like you should be able to use my integration. What energy mode do you run your box in?

**Comment by IngmarG** [comment]
> > Can you show me login screens (with sensitive data obfuscated) you see when you are lgging in on the web environment of Telenet?
> 
> Here are some screenshots from the telenet tv login procedure. ![telenet_01](https://private-user-images.githubusercontent.com/149004029/289664377-8bc9826d-27c0-4917-847f-83d129775f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzg3NjksIm5iZiI6MTcwMjMzODQ2OSwicGF0aCI6Ii8xNDkwMDQwMjkvMjg5NjY0Mzc3LThiYzk4MjZkLTI3YzAtNDkxNy04NDdmLTgzZDEyOTc3NWYzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWUxNDU2YjdmOTVkZWQwNzIzNjRkNzE4NzhlZjNlMmQ3OTEyODIyMTYwZTk5NDMzZTIxZDQ5Zjg4NzJlOGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjtcQhFAZNZaCE9CFEsuaQ3g6IFyfMAYLOIz9bkZTg0) ![telenet_02](https://private-user-images.githubusercontent.com/149004029/289664386-1d44481b-dc46-4310-818f-72125da21479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzg3NjksIm5iZiI6MTcwMjMzODQ2OSwicGF0aCI6Ii8xNDkwMDQwMjkvMjg5NjY0Mzg2LTFkNDQ0ODFiLWRjNDYtNDMxMC04MThmLTcyMTI1ZGEyMTQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGM5Mzg5ODg2ZmY4MTk4NmFjMzY5ZTBkNmFlZTJjNjE1ODVmMDU5ZjcwZTdkNTI1OTgxYWY3ODk2ZjFjNTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BfzMfF1w1KmabvqKME_7tmeQK0Lm-8wabVIHMf7k2Uk) ![telenet_03](https://private-user-images.githubusercontent.com/149004029/289664387-b7d7058d-433c-42a3-851d-263c44b8ed75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMzg3NjksIm5iZiI6MTcwMjMzODQ2OSwicGF0aCI6Ii8xNDkwMDQwMjkvMjg5NjY0Mzg3LWI3ZDcwNThkLTQzM2MtNDJhMy04NTFkLTI2M2M0NGI4ZWQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQyMzQ3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDcxOTUyYzUxMmM0MDI3M2U4NWZiZmM0YTc5MDg2MTVlNWNlZDBjZDQ2OWY5MDAyNzBiMTFjOWQzZmU3YTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9o87SzszPU_FO74Gzpa7f90QZPpVvUv08iuFCugFkII)
> 
> I'm happy to help if you need something specific/more.

Did you manage to login to that page?
Because I can't login on telenet.tv anymore.
![image](https://github.com/Sholofly/lghorizon/assets/10654676/f1c99207-f4cd-4fd1-ad88-8106da3e93a9)
The moment I click login:
![image](https://github.com/Sholofly/lghorizon/assets/10654676/eb6955fc-c1c2-4e27-acd9-e6f1baaebf9e)

**Comment by Mjimsas** [comment]
@IngmarG Yes the login itself from the webpanel works on my side.

**Comment by IngmarG** [comment]
Hmm weird. I can see the page with MyTV, with the channels, with ..., but whenever I click login, I get the error. I can;'t even type my login.
All cookies are accepted, and no scripts are blocked.
This happens on both Edge and Chrome .

**Comment by IngmarG** [comment]
Hmm weird. I can see the page with MyTV, with the channels, with ..., but whenever I click login, I get the error. I can;'t even type my login.
All cookies are accepted, and no scripts are blocked.
This happens on both Edge and Chrome .

**Comment by Mjimsas** [comment]
> @Mjimsas Thank you for the screens. It looks like you should be able to use my integration. What energy mode do you run your box in?

@Sholofly The box is setup for "Fast start" with a stand-by timer of 6 hours.

**Comment by IngmarG** [comment]
> > @Mjimsas Thank you for the screens. It looks like you should be able to use my integration. What energy mode do you run your box in?
> 
> @Sholofly The box is setup for "Fast start" with a stand-by timer of 6 hours.

Same here

**Comment by Mjimsas** [comment]
@IngmarG Might sound stupid but you could try from a private window or delete the browser cache to see if that is interfering in some shape or form.
Otherwise i would try from another device, maybe even on a different network to see if it also happens there.

**Comment by IngmarG** [comment]
> @IngmarG Might sound stupid but you could try from a private window or delete the browser cache to see if that is interfering in some shape or form. Otherwise i would try from another device, maybe even on a different network to see if it also happens there.

Not stupid. Tried that.
Incognito chrome, Privater Edge, cache cleared, cookies enabled, noscript disabled, AV disabled, ...
Didn't try another PC. Tomorrow.

**Comment by 1aranzant** [comment]
Are you perhaps using another service that calls the api?
I had issues using this and homebridge-eosstb at the same time... you have to pick one.

**Comment by IngmarG** [comment]
> Are you perhaps using another service that calls the api? I had issues using this and homebridge-eosstb at the same time... you have to pick one.

Don't know what changed, but it is working again.

**Comment by Roeli1996** [comment]
Good afternoon

I also cannot complete the configuration.
Login is certainly correct, username: email address.

We only have a shared profile, so no multiple users. I cannot find the DTV_identifier on the website, so I have not tried this option for the time being.

Configuration info: Unknown error occurred

**Extra info:** 
- I have Adguard running, but I also can't login without Adguard running. I'm on the latest version of Home Assistant. 
- TVbox: Telenet TV Box (2008C-STB-TN)
- No lines in logfiles


Anyone have an idea?

Thanks in advance for viewing this. 
Best wishes for next year.

_________________________________________________
**Edit:**
When I access Home Assistant locally (homeassistant.local) the loading wheel keeps spinning. Without further errors.

The above error (Unknown error occurred) occurs when I access Home Assistant via XXX.duckdns.org.

**Comment by Dimitry1977** [comment]
I have uninstalled the files.Reinstalled all and all works now.
    Verzonden vanuit Outlook voor iOS
  

 Van: Arne ***@***.***>Verzonden: zondag, december 31, 2023 3:26 PMAan: Sholofly/lghorizon ***@***.***>CC: Dimitry1977 ***@***.***>; Mention ***@***.***>Onderwerp: Re: [Sholofly/lghorizon] Unable to login (Telenet BE) (Issue #65) 
Good afternoon
I also cannot complete the configuration.
Login is certainly correct, username: email address.
We only have a shared profile, so no multiple users. I cannot find the DTV_identifier on the website, so I have not tried this option for the time being.
Configuration info: Unknown error occurred
Extra info:

I have Adguard running, but I also can't login without Adguard running. I'm on the latest version of Home Assistant.
TVbox: Telenet TV Box (2008C-STB-TN)
No lines in logfiles

Anyone have an idea?
Thanks in advance for viewing this.
Best wishes for next year.

**Comment by darkpainy** [comment]
I have the same issue, wheel keeps on turning and eventually thows error: Unknown error occurred
2024-01-11 08:52:24.059 ERROR (SyncWorker_14) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (OSError: [Errno 113] Host is unreachable)

![image](https://github.com/Sholofly/lghorizon/assets/8872709/d283edfc-cdd1-41e5-b523-384f7d8fd4d5)


Kind regards and best wishes for 2024.

**Comment by BernsBe** [comment]
Hi,
I also have the same issue. It started after updating the core to 2024.1.2. Now am at 2024.1.3, still same issue.
Have removed the entire lghorizons repository and removed the integration from the HACS interface. Then re-downloaded, restarted HASS and reconfigured.

After restarting and re-iterating the lg horizon integration from the HASS integration interface still the same:
When filling in login details, the Interface keeps looping, not accepting the credentials (these credentials are working on the telenet.tv web interface.)

**Comment by rudi159** [comment]
Hello,

Same story as from BernsBe here above.

Error in logfile:
```
Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.11/site-packages/backoff/_common.py:120
First occurred: 09:41:46 (2 occurrences)
Last logged: 09:42:47

Giving up connect(...) after 11 tries (ConnectionRefusedError: [Errno 111] Connection refused)
```

Error in Extend logfile:
```
2024-01-13 09:41:46.707 ERROR (SyncWorker_12) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (ConnectionRefusedError: [Errno 111] Connection refused)
2024-01-13 09:41:51.883 ERROR (MainThread) [homeassistant.helpers.entity] Failed to set state for sensor.solaxloc_inverter_data, fall back to unknown
```
Credentials are ok on Web-TV from Telenet

Kind regards

**Comment by BernsBe** [comment]
Have now tried with versions
0.5.3
0.5.2
0.5 1

Same problem with all 3 versions.

**Comment by rudi159** [comment]
Installing the beta-version v0.5.4b1 resolved my problem with registering the integration with Telenet.
Everything is working as before.

Thanks sholofly!

**Comment by Roeli1996** [comment]
Hi

Problem is indeed solved in beta-version v0.5.4b1. Everything is working again.

Thank you for the update Sholofly!

**Comment by BernsBe** [comment]
Thank you sso much Sholofly!!!

I tried with the beta versions and did not succeed.
Planned to do a clean approach this morning.
However, I just installed the brand new 0.5.4 version this way!!!

1) rm -r whole lghorizon directory
2) in HACS add-ons removed lghorizon
3) reboot system entirely (its an RPi 4)
4) installed v0.5.4 using HACS - system message: reboot needed (with link to reboot functionality and all)
5) reboot system entirely
6) verify in HACS if install succeeded (no red message to reboot present, so all OK)
7) provided telenet credentials (no DTV identifier needed in my case)

**Comment by Roeli1996** [comment]
Unfortunately I lost access again. I'll check later today to make sure my box is no longer on energy saving mode. It went wrong yesterday as soon as I opened Netflix on the box.

**Comment by Sholofly** [comment]
> Thank you sso much Sholofly!!!
> 
> I tried with the beta versions and did not succeed. Planned to do a clean approach this morning. However, I just installed the brand new 0.5.4 version this way!!!
> 
> 1. rm -r whole lghorizon directory
> 2. in HACS add-ons removed lghorizon
> 3. reboot system entirely (its an RPi 4)
> 4. installed v0.5.4 using HACS - system message: reboot needed (with link to reboot functionality and all)
> 5. reboot system entirely
> 6. verify in HACS if install succeeded (no red message to reboot present, so all OK)
> 7. provided telenet credentials (no DTV identifier needed in my case)

Not sure, does it work for you, or doesn't it?

**Comment by Sholofly** [comment]
> Unfortunately I lost access again. I'll check later today to make sure my box is no longer on energy saving mode. It went wrong yesterday as soon as I opened Netflix on the box.

@Roeli1996 Can you view the logs. I guess there's something useful there.

**Comment by Roeli1996** [comment]
> > Unfortunately I lost access again. I'll check later today to make sure my box is no longer on energy saving mode. It went wrong yesterday as soon as I opened Netflix on the box.
> 
> @Roeli1996 Can you view the logs. I guess there's something useful there.

Yesterday evening's logging: 
```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 17 januari 2024 om 22:13:03 (4 occurrences)
Last logged: 09:28:38

Error setting up entry EMAIL@EMAIL.BE for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError: Global task timeout
```

I'm using Adguard and I have an Unifi netwerksetup. 


Arne

**Comment by Sholofly** [comment]
@Roeli1996 It doesn't look like a integration problem but a connection issue. Is there something in your setup that blocks the traffic?

**Comment by BernsBe** [comment]
> > Thank you sso much Sholofly!!!
> > I tried with the beta versions and did not succeed. Planned to do a clean approach this morning. However, I just installed the brand new 0.5.4 version this way!!!
> > 
> > 1. rm -r whole lghorizon directory
> > 2. in HACS add-ons removed lghorizon
> > 3. reboot system entirely (its an RPi 4)
> > 4. installed v0.5.4 using HACS - system message: reboot needed (with link to reboot functionality and all)
> > 5. reboot system entirely
> > 6. verify in HACS if install succeeded (no red message to reboot present, so all OK)
> > 7. provided telenet credentials (no DTV identifier needed in my case)
> 
> Not sure, does it work for you, or doesn't it?

Oh, sorry, was not clear enough.
The procedure above, with version 0.5.4 works perfectly.

I did not even have to modify/reprogram the existing automations (that use the TV box status).
Thank you very much.

**Comment by Roeli1996** [comment]
> @Roeli1996 It doesn't look like a integration problem but a connection issue. Is there something in your setup that blocks the traffic?

Good morning

I use AdGuard, other than that I don't think there are anything that could block anything. Furthermore, I do not have a standard network setup:

1) Telenet Modem, which forwards everything to an Ixon.
2) Ixon (VPN device) to Pi 4.
3) Pi as DHCP, including Adguard

Furthermore, a complete Unifi setup. No special settings.
I'll try again this evening without the AdGuard. Thanks for your feedback!


Arne

**Comment by darkpainy** [comment]
@Roeli1996 VPN to where? if you use IP outside of Belgium the integration won't work because the login landing page then requires a Captcha

**Comment by Sholofly** [comment]
Yes @Roeli1996, I guess that's your issue, If the login detects you're outside Belgium, you can't use Telenet....

**Comment by Roeli1996** [comment]
Good evening everyone

Just to clarify, I am not currently using the VPN. I log in from Belgium. The Ixon is just there, so that I can log in to all devices in our home from anywhere (especially Belgium).

I suspect the problem comes from AdGuard, if it is actually a connection problem. Furthermore, my Pi4 is the DHCP server. I use DuckDNS to log in when I am not on my local network.
Although I am now trying to log in via my local network (homeassistant.local).
The integration has been working in my parental home for several years without any problems. I'm not sure what's wrong with my setup. What is also possible: I "bypass" the modem, all traffic is forwarded to a device higher up in my network. Should you use the telent modem, as DHCP and as DNS? I will soon change everything to Telenet to test this. I have a similar problem with my Spotify token when starting Spotcast..

Thanks for your help!

**Comment by BernsBe** [comment]
@roeli1996

I have a separate DHCP and a local DNS on my network, and a different main router between my network and the Telenet modem. (Telenet thus can see only one device in "mijn Telenet").
All works fine here.

Looking forward to see your results.

**Comment by Sholofly** [comment]
Should be solved now. Please open new issue if it still don't work.

**Comment by Roeli1996** [comment]
Hi

Thank you very much! I'm currently able to use the integration. Problem solved for me!


Arne
