### ISSUE TITLE
Automation with double/triple numbers

### ISSUE THREAD

**Issue by Fliha** [Sholofly/lghorizon#68]
Hello,

I want to make a automation for my wife (mostly for my learning curve) that turns the tv on at specific time and channel. 

When I want to choose a channel with 2 numbers, nothing happens. 

action:
  - service: lghorizon.remote_key_press
    data:
      entity_id: media_player.mediabox_woonkamer
      remote_key: "34"
mode: single

I tried several options, but nothing worked (my lack of knowledge I think)

When somebody can help me with this "probably" small thing, I would be grateful

**Comment by Sholofly** [comment]
Hai @Fliha,

Have you tried this?
https://github.com/Sholofly/lghorizon#service-to-change-channel

The remote_key_press kan handle one key at the time. You can use that service but you have to execute it for every digit.
