### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by hessel-a** [Sholofly/lghorizon#69]
> service: lghorizon.play_media
> service_data:
>   entity_id: media_player.ziggo_beneden
>   media_content_id: 401 # Any channel number, 'Netflix' or 'Videoland'

This service is written down in the README. But i can not find it back in homeassistant and no mention in. services.yaml

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version of the component**
The version of the component as it is installed on your HA

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by Sholofly** [comment]
@hessel-a, good point. De provided information was not correct. The service you have to use is media_player.play_media. I've updated the docs. Thanks m8!
