### ISSUE TITLE
Ziggo next mini yaml example

### ISSUE THREAD

**Issue by slingshot74** [Sholofly/lghorizon#72]
I don't know if this is the right way to ask. If not I apoligize upfront.

I would really like to use this coponent, it looks very promising!
But I don't know how to add the custom services.

Does someone has a working yaml of the ziggo next mini which I can use a starting point?

Thank you very much in advance!

**Comment by Sholofly** [comment]
Hi @slingshot74, What is not working for you? What custom services do you want to use?
apart from te regular media_player services there are a few dedicated services for this component:

![image](https://github.com/Sholofly/lghorizon/assets/901632/e53f3649-5753-486c-a405-64cdbd1ded42)

**Comment by Sholofly** [comment]
Still need help?

**Comment by Sholofly** [comment]
@slingshot74 The docs proved to be wrong. I've updated it.
