### ISSUE TITLE
Custom services not working, Service to change channel works - what am I doing wrong

### ISSUE THREAD

**Issue by ArnolddeBolster** [Sholofly/lghorizon#75]
I got the service to change channel working:
service: media_player.play_media
data:
  entity_id: media_player.mediabox
  media_content_id: 1
  media_content_type: channel

But I can't get custom services working.
How can I solve this. The examples in documentation do not help for me.

**Comment by Jouke-87** [comment]
Same here, only for me the channels work but the apps on the platform do not. (Ziggo Next)
Netflix, Videoland, Prime Video...


service: media_player.play_media
target:
  entity_id:
    - media_player.mediabox
  device_id: []
  area_id: []
data:
  media_content_id: Netflix
  media_content_type: app

**Comment by ArnolddeBolster** [comment]
For me this workes on ZiggoNext:
    sources:
      - name: Netflix
        icon: mdi:netflix
      - name: Disney+
        icon: disney
      - name: Prime Video
        icon: si:amazonaws
      - name: Viaplay info
        icon: si:v
you can find the sources in developmenttools(ontwikkelhulpmiddelen>status(statussen). You must lteraly name as in the source_list

I have added an ectra row with these buttons which are not available in the source_list but wanted to assign them to scripts which are working:
      - name: Menu
        icon: mdi:menu
      - name: Teletekst
        icon: mdi:format-text
      - name: TV Guide
        icon: mdi:television-guide
      - name: DVR
        icon: mdi:video

**Comment by ArnolddeBolster** [comment]
In the description is mentioned to name the source as app eg:
service: media_player.play_media
data:
entity_id: media_player.mediabox
media_content_id: Netflix
media_content_type: app

**Comment by Sholofly** [comment]
The examples are a little off. You should use data instead of service_data. i.e.:

```yaml
service: lghorizon.remote_key_press
data:
  entity_id: media_player.ziggo_beneden
  remote_key: MediaTopMenu
```

Sorry for the inconvenience. I'll change the docs.

**Comment by Jouke-87** [comment]
> In the description is mentioned to name the source as app eg: service: media_player.play_media data: entity_id: media_player.mediabox media_content_id: Netflix media_content_type: app

Sorry Prime Video works, Netflix and Videoland do not.

I have tried various configurations but nothing works. It goes to the channel but does not open Netflix. If I go to that channel with my normal remote bidding, it works. If I set 'channel' and the Netflix channel number to '114', for example, it doesn't work either.


tap_action:
  action: call-service
  service: media_player.play_media
  data:
    entity_id: media_player.mediabox
    media_content_id: Netflix
    media_content_type: app

**Comment by ArnolddeBolster** [comment]
@Sholofly Many thanks for your answer. I now have most of the remote buttons of the ZiggoNext added to to LG WEBOS Remote which I use in combination as universal remote. Most of the universal remote buttons I earlier used with scripts from Logitech Harmony remote.
Probably more commands can be triggered with your solution so i post all commands i have:
Ziggo Next
{"deviceId":"","command":"Power","action":"press"}
"deviceId":"","command":"0","action":"press"}
{"deviceId":"","command":"1","action":"press"}
{"deviceId":"","command":"2","action":"press"}
{"deviceId":"","command":"3","action":"press"}
{"deviceId":"","command":"4","action":"press"}
{"deviceId":"","command":"5","action":"press"}
{"deviceId":"","command":"6","action":"press"}
{"deviceId":"","command":"7","action":"press"}
{"deviceId":"","command":"8","action":"press"}
{"deviceId":"","command":"9","action":"press"}
{"deviceId":"","command":"Mute","action":"press"}
{"deviceId":"","command":"VolumeDown","action":"press"}
{"deviceId":"","command":"VolumeUp","action":"press"}
{"deviceId":"","command":"ChannelPrev","action":"press"}
{"deviceId":"","command":"ChannelDown","action":"press"}
{"deviceId":"","command":"ChannelUp","action":"press"}
{"deviceId":"","command":"DirectionDown","action":"press"}
{"deviceId":"","command":"DirectionLeft","action":"press"}
{"deviceId":"","command":"DirectionRight","action":"press"}
{"deviceId":"","command":"DirectionUp","action":"press"}
{"deviceId":"","command":"Select","action":"press"}
{"deviceId":"","command":"Stop","action":"press"}
{"deviceId":"","command":"Play","action":"press"}
{"deviceId":"","command":"Rewind","action":"press"}
{"deviceId":"","command":"Pause","action":"press"}
{"deviceId":"","command":"FastForward","action":"press"}
{"deviceId":"","command":"Record","action":"press"}
{"deviceId":"","command":"Menu","action":"press"}
{"deviceId":"","command":"Back","action":"press"}
{"deviceId":"","command":"Teletext","action":"press"}
{"deviceId":"","command":"DVR","action":"press"}
{"deviceId":"","command":"Green","action":"press"}
{"deviceId":"","command":"Red","action":"press"}
{"deviceId":"","command":"Blue","action":"press"}
{"deviceId":"","command":"Yellow","action":"press"}
{"deviceId":"","command":"Guide","action":"press"}
{"deviceId":"","command":"Info","action":"press"}
{"deviceId":"","command":"Exit","action":"press"}
{"deviceId":"","command":"Help","action":"press"}
{"deviceId":"","command":"OnDemand","action":"press"}
