### ISSUE TITLE
This integration will stop working after The next home assistant update 

### ISSUE THREAD

**Issue by hessel-a** [Sholofly/lghorizon#79]
**Describe the bug**
After updating to the next beta this integration not available anymore. And you need to find your remote again to control

**To Reproduce**
2023.12.4 In this version it still runs. After version 2024.1.0b0 it is not more available/running

**Expected behavior**

**Screenshots**

**Version of the component**

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by Sholofly** [comment]
Thanks for reporting. I'm on it!
