### ISSUE TITLE
Error in Service.yaml 

### ISSUE THREAD

**Issue by snhnic** [Sholofly/lghorizon#88]
I get after every update an error in Watchman report about missing entity: media_player.tv_box_livingroom

Seems an easy fix, just in services. yaml an # and  problem solved, can you implement this in future updates? 

`record:
  fields:
    entity_id:
      # example: "media_player.tv_box_livingroom"

rewind:
  fields:
    entity_id:
      # example: "media_player.tv_box_livingroom"

fast_forward:
  fields:
    entity_id:
      # example: "media_player.tv_box_livingroom"

remote_key_press:
  fields:
    entity_id:
      # example: "media_player.tv_box_livingroom"
    remote_key:
      # example: TV`

**Comment by Sholofly** [comment]
Hi there, since 'example' isvalid syntax for home assistant service descriptions I'm not going to remove it. It's to the developer of the custom Watchman integration to solve this (I agree) annoying warning.

**Comment by snhnic** [comment]
Why its just simple to change this and it would help. Every update you make, I have to do the same thing to avoid the error. Just put in # and my problem will be gone. I think it is not a valid code since it is an example and should be with a remark #

**Comment by Sholofly** [comment]
The example field is used to fill the service in the developers tab. If I prefix it with a hash that doesn't work anymore.

**Comment by snhnic** [comment]
Okay I understand. Than let it stay, I will change it at every update. No probs.
