### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by schol478** [Sholofly/lghorizon#9]
I'm missing the service lghorizon to change a channel in Home assistant version 2022.10.5.

**Comment by Sholofly** [comment]
Changing the channel by name is available using the media_player.select_source service
Emulating key presses (to change channel) is available in beta only. Is that what you mean?

**Comment by Ton-O** [comment]
Great work, thank you!
Probably still not possible within the API: possibility to switch to a "Radio channel".
API allows, but LG-box is not changing.

**Comment by Sholofly** [comment]
The radio channels are in the list. But you can't switch to it. I'm going to check it out

**Comment by Sholofly** [comment]
Switching to radio channels isn't possible at all ATM. I am sorry.

**Comment by Ton-O** [comment]
I expected that already; but as I don't know the source of your info, I just tried.
Thanks for checking and getting back! And of-course, the good work you've produced!
