### ISSUE TITLE
Complete freezing of HA at random intervals

### ISSUE THREAD

**Issue by medivb** [Sholofly/lghorizon#91]
Using blank template as I have no clue how to approach this.

My HA system started to freeze at random intervals on newyears eve. This literally never happened before. After going through a determination flow of disabling and re-enabling of add-ons I was able to narrow the root cause down to the lghorizon add-on, which I had been using since the first release, am extremely happy with and which had never caused an issue before. It seems that the 0.5.3 release introduced something causing this.

I really hope this rings a bell somehow and I am willing to test stuff if needed to help, but might need some guidance as I am a true linux noob. I did update to 0.5.4, but left the add-on disabled for now.

I use Ziggo with 2 mediabox next mini receivers in the Netherlands.

Thanks for the great work and effort you guys put into this! Highly appreciated!

**Comment by JBakers** [comment]
You could start by providing a debug log, system info, etc?

The template is there for a reason.

**Comment by Sholofly** [comment]
Please feel free to continue in #90
