### ISSUE TITLE
Network unreachable

### ISSUE THREAD

**Issue by richardx95** [Sholofly/lghorizon#99]
I got the plugin running and I can see my recorded programs and the recording capacity.
But for some reason the ‘mediabox’ entity is unavailable. Anybody knows why?

This is the logging error;

`2024-01-20 18:26:36.867 ERROR (SyncWorker_2) [homeassistant.components.ziggo_mediabox_xl.media_player] Can't connect to 192.168.0.123: HTTPSConnectionPool(host='restapi.ziggo.nl', port=443): Max retries exceeded with url: /1.0/channels-overview (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83d15f10>: Failed to establish a new connection: [Errno 101] Network unreachable'))`

Is there a way to change the networking settings

**Comment by lapodomo** [comment]
somthing likewise here after reboot has, it wont even start and hangs on the lghorizon plugin after disabling this plugin has continues starting:
`Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.11/site-packages/backoff/_common.py:120
First occurred: 17:02:35 (5 occurrences)
Last logged: 17:10:14

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)
Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)`

**Comment by sdotter** [comment]
Ive got same... rebooted ziggo next updated to latest lghorizon hass component...  but same: 

Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-prod-nl.gnp.cloud.ziggogo.tv/auth-service/v1/mqtt/token)

**Comment by Braakie** [comment]
Here are also the problems with Ziggo Netherlands on the Mediabox Next
Uninstalled the integration and reinstalled it. The login process does not go well and it hangs.

Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.0

Here the debug log:
[home-assistant.log](https://github.com/Sholofly/lghorizon/files/14206757/home-assistant.log)

**Comment by Sholofly** [comment]
Is this still an issue?

**Comment by Sholofly** [comment]
Stale
